run:
  tests: false
  timeout: 10m
  modules-download-mode: readonly
  allow-parallel-runners: false
linters:
  enable-all: true
  disable:
    # obsolete linters
    - depguard
    - exportloopref
    - gofumpt
    - nlreturn
    - wrapcheck
    - wsl
